Repository NullVoxPopuli/ember-router-scroll, pull requests merged in 2025-04, with the labels that each got.

#1 Implementation
  .github/workflows/ci.yml
  .gitignore
  .try.mjs
  README.md
  babel.config.cjs
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  public/images/death-star.png
  public/images/stars.png
  public/images/tentacle-monster.png
  public/images/yellow_submarine.gif
  rollup.config.mjs
  src/instance-initializers/ember-router-scroll.js
  src/scheduler.ts
  src/services/router-scroll.js
  src/template-registry.ts
  testem.js
  tests/application-test.gjs
  tests/index.html
  tests/service-test.js
  tests/styles.css
  tests/test-app/application.gjs
  tests/test-app/next-page.gjs
  tests/test-app/target-next-page.gjs
  tests/test-app/target.gjs
  tests/test-helper.js
Labels: enhancement

#2 npx create-release-plan-setup@latest --update
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  CHANGELOG.md
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#5 Inject as Service Deprecation Warning Fix
  README.md
  src/services/router-scroll.js
Labels: bug
